theme: jekyll-theme-dinky
logo: https://avatars0.githubusercontent.com/u/46445292
title: preferans-score-js
description: preferans score
show_downloads: "true"
include:
  - "_*_.html"
  - "_*_.*.html"
plugins:
  - jemoji